site_name: Documentação

nav:
  - Visão do Produto e Projeto : "visao-projeto-produto/visaoprojetoproduto.md"
  - Atas de Reunião:
    - Ata 1: "atas-reuniao/ata-reuniao-1.md"

theme:
  name: material