site_name: GestFarma

nav:
  - Visão do Produto e Projeto: "visao-projeto-produto/visaoprojetoproduto.md"
  - Backlog: "visao-projeto-produto/backlog.md"
  - MVP: "visao-projeto-produto/mvp.md"
  - Processo de Desenvolvimento de Software: "processo-de-desenvolvimento-de-software/diagrama.md"
  
  - Apêndice:
      - Regras de Negócio: "visao-projeto-produto/regrasdenegocio.md"

theme:
  name: material
